modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="the_knocker"
version="1.2.0"
displayName="The Knocker"
displayURL="https://discord.gg/uH6ybdaG"
logoFile="logo.png"
credits="Ma_Do"
authors="Ma_Do"

[[dependencies.the_knocker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




